robotiq_2f_85:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  left_controller:
    type: position_controllers/JointGroupPositionController
    joints: 
      - finger_joint
      - left_inner_knuckle_joint
      - left_inner_finger_joint
    pid_gains:
      finger_joint: {p: 100.0, i: 0.01, d: 10.0}
      left_inner_knuckle_joint: {p: 100.0, i: 0.01, d: 10.0}
      left_inner_finger_joint: {p: 100.0, i: 0.01, d: 10.0}
  right_controller:
    type: position_controllers/JointGroupPositionController
    joints: 
      - right_outer_knuckle_joint
      - right_inner_knuckle_joint
      - right_inner_finger_joint
    pid_gains:
      right_outer_knuckle_joint: {p: 100.0, i: 0.01, d: 10.0}
      right_inner_knuckle_joint: {p: 100.0, i: 0.01, d: 10.0}
      right_inner_finger_joint: {p: 100.0, i: 0.01, d: 10.0}