robotiq_2f_85:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  gripper_controller:
    type: position_controllers/JointPositionController
    joint: finger_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}